#Enable RGB color and undercurl support
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors

# set -g prefix C-a
# unbind C-b
# bind-key C-a send-prefix
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file ~/.tmux.conf

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

bind M-c attach-session -c "#{pane_current_path}"

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse


# status bar styling 
#pallete from: https://www.color-hex.com/color-palette/1080089
deep_plum="#4a2c5a"
greenish_teal="#5ed3d1"
melody="#cbb4e8"
electric_banana="#f4d35e"
peachy_peach="#f7b89c"

set -g status-position bottom
set -g status-left-length 100
set -g status-style "fg=default,bg=default" # bg : transparent

set -g window-status-format " #I  #W"
set -g window-status-current-format "#[fg=${electric_banana},bold]  #[underscore]#I  #W"

set -g status-right "#[fg=${greenish_teal},bold]   #S "
set -g message-style "fg=${greenish_teal},bg=default"
set -g mode-style "fg=${deep_plum},bg=${greenish_teal}"


# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'tmux-plugins/tmux-yank' # add the yank to clipboard
set -g @plugin 'tmux-plugins/tmux-sensible' # A set of tmux options that should be acceptable to everyone

set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
#set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes


set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
